### PR TITLE
Syslog support

### LINKED ISSUE #101: Add syslog capabilities
We want to be able to log to syslog

### PR DESCRIPTION
**Pull request by fmorency**
Make use of the `tracing-syslog` repo at https://github.com/max-heller/tracing-syslog

See https://github.com/tokio-rs/tracing/pull/1137 for the whole story.

I tested this using `syslog-ng`. When the `syslog` service is not running, messages are still written to the log files and get picked up when the service restarts.

Fixes #101

@hansl this crate is not on crates.io and this PR uses the git repo directly, fixed to a rev. I don't know the author's intention moving forward but we might want to fork this until/if it gets integrated into the `tokio` tracing ecosystem. WDYT?

Also, this feature is currently not optional. Do you want me to add a `--syslog` flag to the binaries?

### CODE REVIEW

**Comment by hansl** [comment]
Make the flag `--logmode=syslog` that way we can have multiple different modes (like json, term).

**Comment by hansl** [comment]
Let's reach out to @max-heller to see if he'd need a home for that crate (we could have it in liftedinit) or if he's planning to maintain it and publish it soon. It seems simple enough.

**Review by hansl — APPROVED** [review]
LGTM with the change from stdout to stderr

**Comment by max-heller** [comment]
> Let's reach out to @max-heller to see if he'd need a home for that crate (we could have it in liftedinit) or if he's planning to maintain it and publish it soon. It seems simple enough.

Published as [`syslog-tracing`](https://crates.io/crates/syslog-tracing), I was trying to get ownership of the name-squat [`tracing-syslog`](https://crates.io/crates/tracing-syslog) but couldn't get in contact with the owner.

**Pull request merged**
